# Batch size used when the model performs predictions
PREDICTION_BATCH_SIZE = 1
# Batch size used for model training
TRAINING_BATCH_SIZE = 1

# Controls how the images generated by this project are provided.
# If False, images are displayed in a window. If True, images are saved in <project root>/images
SAVE_IMAGES_ON_DISK = True